server:
  port: 8080

spring:
  cloud:
    gateway:
      mvc:
        routes: []

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"